export default {
  content: [
    "./frontend/**/*.html",
    "./frontend/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#b7c8e1",
        "tertiary-fixed": "#d3e4fe",
        "on-secondary-container": "#00732c",
        "secondary-fixed-dim": "#3ce36a",
        "outline": "#737780",
        "surface": "#f7f9fb",
        "on-primary-container": "#799dd6",
        "secondary": "#006e2a",
        "outline-variant": "#c3c6d1",
        "surface-container-high": "#e6e8ea",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#002108",
        "surface-container-highest": "#e0e3e5",
        "inverse-primary": "#a7c8ff",
        "on-primary": "#ffffff",
        "primary-container": "#003366",
        "on-tertiary-fixed-variant": "#38485d",
        "tertiary-container": "#243448",
        "background": "#f7f9fb",
        "inverse-surface": "#2d3133",
        "surface-bright": "#f7f9fb",
        "surface-container": "#eceef0",
        "surface-container-low": "#f2f4f6",
        "on-tertiary": "#ffffff",
        "primary": "#001e40",
        "primary-fixed": "#d5e3ff",
        "surface-tint": "#3a5f94",
        "tertiary": "#0e1f32",
        "surface-variant": "#e0e3e5",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-container": "#5cfd80",
        "on-primary-fixed": "#001b3c",
        "on-secondary-fixed-variant": "#00531e",
        "on-surface": "#191c1e",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#0b1c30",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#43474f",
        "secondary-fixed": "#69ff87",
        "on-tertiary-container": "#8c9cb5",
        "on-primary-fixed-variant": "#1f477b",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed-dim": "#a7c8ff",
        "on-background": "#191c1e"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "32px",
        "gutter": "16px",
        "sm": "16px",
        "base": "4px",
        "container-margin": "20px",
        "xs": "8px",
        "xl": "48px",
        "md": "24px"
      }
    }
  },
  plugins: [],
}
